/**
 * 定义类型常量
 */

const INCREMENT='INCREMENT'
const DECREMENT='DECREMENT'
const SAVEUSERINFO='SAVEUSERINFO'
const SETCURSTATS='SETCURSTATS'
const SETALLSTATS='SETALLSTATS'
const HANDLESTATS='HANDLESTATS'
export default {
	INCREMENT,
  DECREMENT,
  SAVEUSERINFO,
  SETCURSTATS,
  SETALLSTATS,
  HANDLESTATS
}
