/**
 * 定义类型常量
 */

const INCREMENT='INCREMENT'
const UPDATETODAYFINISHMATTERS='updateTodayFinishMatters'

const UPDATEFINISHMATTERSCOUNT='updateFinishMattersCount'
const  UPDATELASTMATTERSTATS='updateLastMatterStats'



export default {
  INCREMENT,
  UPDATETODAYFINISHMATTERS,
  UPDATEFINISHMATTERSCOUNT,
  UPDATELASTMATTERSTATS
}
